# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54391bf25eb23c4c0886fbf6919276a9a4910f8eaba0a7b886f284d1e8d6d05f373a5ffcbd7239c9092d37c493e19f8036d37087fc65d52ecc555d181b4bb174

test:
  secret_key_base: c5a9ac793a25db2e34a217ec7f6664e3b9acea62dcbdd983a17f52bd9d00326aed2f28bdd474b78823f8ab945b47120f1fa3dc5a618ebacc190b1f2f419d6ac0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
